//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace allpax_sale_miner_3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_customer_eqpmt
    {
        public string customerCode { get; set; }
        public string machineID { get; set; }
        public string eqpmtType { get; set; }
        public int id { get; set; }
    
        public virtual tbl_customer tbl_customer { get; set; }
    }
}
